# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: balance.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbalance.proto\"!\n\x0e\x42\x61lanceRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"\"\n\x0f\x42\x61lanceResponse\x12\x0f\n\x07\x62\x61lance\x18\x01 \x01(\x05\"<\n\x14UpdateBalanceRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x13\n\x0bnew_balance\x18\x02 \x01(\x05\"(\n\x15UpdateBalanceResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x81\x01\n\x0e\x42\x61lanceService\x12/\n\nGetBalance\x12\x0f.BalanceRequest\x1a\x10.BalanceResponse\x12>\n\rUpdateBalance\x12\x15.UpdateBalanceRequest\x1a\x16.UpdateBalanceResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'balance_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BALANCEREQUEST']._serialized_start=17
  _globals['_BALANCEREQUEST']._serialized_end=50
  _globals['_BALANCERESPONSE']._serialized_start=52
  _globals['_BALANCERESPONSE']._serialized_end=86
  _globals['_UPDATEBALANCEREQUEST']._serialized_start=88
  _globals['_UPDATEBALANCEREQUEST']._serialized_end=148
  _globals['_UPDATEBALANCERESPONSE']._serialized_start=150
  _globals['_UPDATEBALANCERESPONSE']._serialized_end=190
  _globals['_BALANCESERVICE']._serialized_start=193
  _globals['_BALANCESERVICE']._serialized_end=322
# @@protoc_insertion_point(module_scope)
